server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/billing_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt: 
          secret-key: ${JWT_SECRET}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: "1.0" # capture all requests (dev only)
    propagation:
      type: w3c

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: "*"