server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/billing_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka