server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
    username: root
    password:
  # Dev only. In production, you'd use migrations with Flyway or Liquibase.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Register on Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# test:
#   message: "Hola desde Config Server"
