server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
    username: root
    password:
  # Dev only. In production, you would use migrations with Flyway or Liquibase.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt: 
          secret-key: ${JWT_SECRET}

# Register on Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Resilience4j
resilience4j:
  retry:
    instances:
      billingService:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          # - feign.FeignException # bad: include 4xx errors (client)
          - feign.FeignException$ServiceUnavailable
          - feign.RetryableException
          - java.io.IOException
          
# CLOSED: all normal
# OPEN: blocking calls
# HALF-OPEN: attempt again
  circuitbreaker:
    instances:
      billingService:
        sliding-window-size: 5 # check record failure of calls
        failure-rate-threshold: 50 # percent fault tolerance
        wait-duration-in-open-state: 10s # circuit blocking in seconds
        permitted-number-of-calls-in-half-open-state: 2

logging:
  level:
    io.github.resilience4j.retry: DEBUG
    org.springframework.cloud.openfeign: DEBUG

# test:
#   message: "Hola desde Config Server"

management:
  tracing:
    sampling:
      probability: "1.0" # capture all requests (dev only)
    propagation:
      type: w3c

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: "*"
